# config file to list all table-specific information for data that must be loaded once to database
# layout should be db table name as key and all else as values


calendarRef:
  bucket_ref: raw_data
  infile: Calendar.txt
  file_type: csv
  delimiter: '\t'
  dtypes:
    CALMM: str