# config file to list all table-specific information for data that must be loaded once to database
# layout should be db table name as key and all else as values


calendarRef:
  bucket_ref: raw_data
  infile: Calendar.txt
  file_type: csv
  readin_kwargs:
    delimiter: '\t'
    dtype:
      CALMM: str

cndsXwalk:
  bucket_ref: raw_data
  infile: TCLD_Alt_CNDS_DOB_DOD.csv
  file_type: csv

tcldStatus:
  bucket_ref: raw_data
  infile: Individual_status_history_data_07192021.csv
  file_type: csv
  fill_nulls:
    Status End: '9999-12-31'
  readin_kwargs:
    parse_dates:
      - Status Begin
      - Status End

hearts:
  bucket_ref: raw_data
  infile: TLCI_Adm_201901_202012_20200806_with_Discharge_Destination.csv
  file_type: csv
  readin_kwargs:
    encoding:
      windows-1252

nctracksProf:
  bucket_ref: raw_data
  infile: NCTracks_PROF_01012020_03312020.csv
  file_type: csv
  readin_kwargs:
    dtype:
      ADMN_CNTY_CD: str
      RES_CNTY_CD: str
      CARR_ID: str
      DMH_LME_BASE_NBR: str

nctracksInst:
  bucket_ref: raw_data
  infile: NCTracks_INST_CYs_2019_2020.csv
  file_type: csv
  readin_kwargs:
    dtype:
      ADMN_CNTY_CD: str
      RES_CNTY_CD: str
      CARR_ID: str
      DMH_LME_BASE_NBR: str


