# config file to list all table-specific information for data that must be loaded once to database
# layout should be db table name as key and all else as values


calendarRef:
  bucket_ref: raw_data
  infile: Calendar.txt
  file_type: csv
  delimiter: '\t'
  dtypes:
    CALMM: str

tcldStatus:
  bucket_ref: raw_data
  infile: Individual_status_history_data_07192021.csv
  file_type: csv

cndsXwalk:
  bucket_ref: raw_data
  infile: TCLD_Alt_CNDS_DOB_DOD.csv
  file_type: csv

tcldStatus:
  bucket_ref: raw_data
  infile: Individual_status_history_data_07192021.csv
  file_type: csv
  parse_dates:
    - Status Begin
    - Status End