# config setup for NC common module

PATHS:
  data_dir: ${BASE_DIR}\2. Data Management\04 Data Sources
  db_design_dir: ${BASE_DIR}\2. Data Management\05 Database Design

FILES:
  data_model: NC AWS Data Model.xlsx

DB_PARAMETERS:
  schema_names: 
    raw: rawdata
  db_cluster_arn: arn:aws:rds:us-east-1:838494257041:cluster:nctcl-rds-db
  db_credentials_secrets_store_arn: arn:aws:secretsmanager:us-east-1:838494257041:secret:rds-db-credentials/cluster-CTRRD427C7XG7CJF7CVP3VSSPU/nctcldevadmin-skZIuQ
  profile: 838494257041_Project_Developer
  region: us-east-1
